### ISSUE TITLE
Megamenu's says "Tried to glitch menu and.."

### ISSUE THREAD

**Issue by Trnrr** [DosMike/MegaMenus#2] opened 2019-04-09 19:53 UTC
Hey spoke on discord the other day. I did some testing and the only client side mod that is active on the server is "ctgui" but that relates to crafttweaker and cant be removed.

How to reproduce.
1. Start server
2. Login
3. Click on the shop entity

After you click on the shop the first time, it will open and you can buy stuff. But it will throw the error in console and wont let you open next time you try.
https://gist.github.com/Trnrr/afac44b1e4ffef88bf8b3d6cae08e174

And then ingame when you right click it, it will give you the error twice even though you right click once. http://puu.sh/DclZM/7fd6fbaa28.png

**Versions:**
Langswitch-1.4
megamenus 0.3
Villagershops 2.0
Sponge/forge: http://puu.sh/Dc4a8/f8e57f33bf.jpg

**Comment by DosMike** [comment] 2019-04-10 07:13
I'd like to know the condition under that you've interacted with the menu; was your inventory/hotbar full/empty, what item did you buy/sell, does any of that matter?
I need to know all that because as i think i said in discord i can't currently reproduce it on my testserver

**Comment by Trnrr** [comment] 2019-04-11 03:32
I will do some testing tomorrow. But it happens both clicking with items in my hand and without. It opens the first time but then cant after that. I'm not sure if this helps or means anything, but when I do `/megamenus:glitch`it gives me a minecraft:stone. I will test tomorrow

**Comment by llronaldoll** [comment] 2019-04-12 04:11
I had the same problem!

**Comment by Kizwiz** [comment] 2019-04-18 22:28
This just happened to me. This is what I did step by step:

**ITEMS IN INVENTORY & HOTBAR:** Wooden Axe (World Edit Tool), Diamond Saw, Coal, Iron bar, Gold Bar, Diamond, Gunpowder, Region Selector (From UniverseGuard), Diamond block, Block of quartz post, block of quartz slab, Gray stained glass slab, Nyarlathotep statue

Thought I do'nt believe the items are the issue as this has occured with items, without items, in survival mode and in creative.

1. Had an empty hand and right clicked the NPC (Minoshroom NPC From Twilight Forest mod)
2. Closed the menu via ESC key
3. Right clicked again to open shop right after
4. Closed the menu via ESC again
5. Attempted to open shop via right click again and greeted with the error message

**Comment by llronaldoll** [comment] 2019-04-18 22:52
this only happens once you add the item to npc, after restarting the server does not happen again!

**Comment by Trnrr** [comment] 2019-04-18 23:01
> 
> 
> this only happens once you add the item to npc, after restarting the server does not happen again!

For me it works the first time on server restart, but if you try and click again it happens again

**Comment by Senidy** [comment] 2019-05-24 13:07
I'm having this same issue on my server. After restarting it lets me use the shop once then it bugs again. I had an empty inventory and bought 1 sand from the shop.

This is the console message:
24.05 13:04:34 [Server] Server thread/INFO [langswitch]: Missing translation shop.title
24.05 13:04:34 [Server] Server thread/INFO [langswitch]: Missing translation shop.title
24.05 13:04:35 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.buy.one
24.05 13:04:35 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.buy.one
24.05 13:04:35 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.sell.one
24.05 13:04:35 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.sell.one
24.05 13:04:35 [Server] Server thread/WARN [megamenus]: Menu was closed or changed during render
24.05 13:04:35 [Server] Server thread/ERROR [megamenus]: Senidy(2b871797-3b6d-43a0-b5c8-11a9b214f081) Tried to glitch a menu and was automatically banned from using menus until the server restarts.
24.05 13:04:35 [Server] Server thread/WARN [megamenus]: Menu was closed or changed during render
24.05 13:04:36 [Server] Server thread/INFO [langswitch]: Missing translation shop.buy.message
24.05 13:04:37 [Server] Server thread/INFO [vshop]: Saving VillagerShops...
24.05 13:04:37 [Server] Server thread/INFO [langswitch]: Missing translation shop.shopowner.missingitems
24.05 13:04:40 [Server] Server thread/INFO [langswitch]: Missing translation shop.title
24.05 13:04:40 [Server] Server thread/INFO [langswitch]: Missing translation shop.title
24.05 13:04:42 [Server] Server thread/INFO [langswitch]: Missing translation shop.chat.transaction.base

**Comment by DosMike** [comment] 2019-06-03 12:17
Is this fixed now?

**Comment by Senidy** [comment] 2019-06-03 12:20
Didn't realize VillagerShops was also updated so took a few tries, but this appears to be fixed now, yes. I'm not sure why I'm missing translations still (using default en_US) but I'll make a post over on the GitHub for LangSwitch for that.

**Comment by DosMike** [comment] 2019-06-10 11:53
Alright, I'll close this issue now.
Thank you to everyone that helped resolve this issue.

**Closed as completed by DosMike** 2019-06-10 11:53 UTC
Labels: bug
